# Generated by Django 5.2.1 on 2025-05-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('PROGRAMMING', 'Programming'), ('DESIGN', 'Design'), ('DATABASE', 'Database'), ('DEVOPS', 'DevOps'), ('FRAMEWORK', 'Framework'), ('TOOL', 'Tool'), ('LANGUAGE', 'Language'), ('OTHER', 'Other')], default='PROGRAMMING', max_length=50),
        ),
    ]
