# Generated by Django 5.2.1 on 2025-05-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_skill_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-display_order', 'name']},
        ),
        migrations.AddField(
            model_name='skill',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Higher numbers appear first'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('PROGRAMMING', 'Programming Languages'), ('WEB', 'Web Development'), ('DATABASE', 'Databases'), ('TOOLS', 'Tools & DevOps'), ('OTHER', 'Other Skills')], default='PROGRAMMING', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(default='fas fa-code', help_text="FontAwesome icon class (e.g., 'fas fa-code')", max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(default=50, help_text='0-100 percentage'),
        ),
    ]
